export const ALL_RESPONSES_SUPPORT = [
   'Disculpe no tengo la información que me esta solicitando, a lo mejor si lo pregunta usando otras palabras pudiera ayudarlo.',
   'Hola, ¿en qué puedo ayudarte hoy?',
   'Lamento los inconvenientes que has tenido, ¿puedes darme más detalles sobre el problema?',
   'Gracias por ponerte en contacto con nosotros. Estamos aquí para ayudarte.',
   'Por favor, verifica tu conexión a Internet y vuelve a intentarlo.',
   '¿Has probado reiniciar el dispositivo o la aplicación?',
   'Podría tomar algunos minutos, pero te mantendremos actualizado sobre el estado de tu solicitud.',
   'Tu solicitud ha sido recibida. Te contactaremos pronto con más detalles.',
   'Si necesitas asistencia adicional, no dudes en comunicarte con nosotros nuevamente.',
   'El equipo de soporte está trabajando en tu caso. Te agradecemos tu paciencia.',
   'Para resolver tu problema, por favor envíanos una captura de pantalla o más detalles.',
   'Estamos verificando la información que proporcionaste y nos pondremos en contacto contigo pronto.',
   'Para obtener más información sobre nuestros productos, visita nuestra sección de preguntas frecuentes.',
   'Lamentablemente, no podemos ofrecerte una solución inmediata, pero te avisaremos tan pronto como tengamos una actualización.',
   'Si tienes alguna pregunta adicional, no dudes en preguntarnos.',
   'Actualmente estamos realizando mantenimiento en el sistema, por lo que algunos servicios pueden no estar disponibles temporalmente.',
   'Gracias por tu paciencia mientras trabajamos en la resolución de tu solicitud.',
   'Tu caso está siendo procesado por el equipo adecuado. Te enviaremos una actualización lo antes posible.',
   'Lo sentimos mucho por los inconvenientes causados. Estamos trabajando para solucionarlo.',
   'Tu solicitud ha sido escalada al departamento correspondiente para una solución más rápida.',
   'Por favor, asegúrate de que todos los datos que proporcionaste sean correctos para que podamos ayudarte de la mejor manera posible.',
   'Este tipo de problemas pueden tardar un poco más en solucionarse, pero haremos todo lo posible para resolverlo lo antes posible.',
   'Si necesitas ayuda con algo más, estaré aquí para ayudarte.',
   'Para obtener ayuda, por favor, proporciónanos tu número de orden o ID de cliente.',
   'Nuestro equipo está investigando el problema. Apreciamos tu paciencia mientras lo solucionamos.',
   'Tu problema está siendo atendido por un experto. Te daremos más detalles en breve.',
   'Apreciamos tus comentarios. Nos ayudan a mejorar nuestros productos y servicios.',
   'Te contactaremos tan pronto como tengamos una solución para ti.',
   'Por favor, mantén abierta esta conversación hasta que te hayamos proporcionado una solución.',
   'Estamos trabajando en tu solicitud y nos pondremos en contacto contigo en breve.',
   'Hemos recibido tu mensaje y nuestro equipo de soporte está al tanto de la situación.',
   'Gracias por tu comprensión mientras resolvemos este problema.',
   'Tu caso está siendo priorizado y te informaremos tan pronto como tengamos más detalles.',
   'Por favor, ten en cuenta que algunos problemas pueden requerir un poco más de tiempo para resolverse.',
   'Si tienes alguna otra pregunta o necesitas más ayuda, no dudes en preguntar.',
];